import Header from "./components/Header";
import "../styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>First App with Nextjs 13</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
